### ISSUE TITLE
Problem about starting an orderer

### ISSUE THREAD

**Issue by SebastianElvis** [jcs47/hyperledger-bftsmart#1]
Hi, I encountered an issue when I want to start an orderer after starting the proxy.
I firstly started 4 replicas, following the README instruction. Then I started a proxy. All of these commands were done without 'sudo'.
However, when I tried to start an orderer by './orderer/orderer', there is a mistake:
![image](https://user-images.githubusercontent.com/9570153/31059663-ef18d24c-a6fd-11e7-934c-8733e3f56c8e.png)
Also the proxy started to log like this:
![image](https://user-images.githubusercontent.com/9570153/31059671-15776002-a6fe-11e7-9c31-fb5b1a6801bc.png)
If I run the proxy with 'sudo', the orderer can start normally but the proxy seems to be untouched. Once I start a timestamp client in the example, the orderer/proxy/stdout are all crashed.
Have you ever encountered this? Thanks you!

**Comment by jcs47** [comment]
Judging from the java exception, I suspect you are using the wrong branch. Make sure you are using the "zeromq" branch at both the HLF fork *and* this repository.

**Comment by SebastianElvis** [comment]
@jcs47 What do you mean for HLF's ZeroMQ branch? Is it the repository https://github.com/jcs47/fabric?
I used this branch and the ZeroMQ branch of BFTSmart. Do these steps require the root privilege? And what is the content in /tmp folder about? Thanks for your time!

**Comment by jcs47** [comment]
Yes, both the zeromq branch of jcs47/fabric and jcs47/hyperledger-bftsmart. Make sure to switch to that branch in both repos and re-compile the code.

**Comment by jcs47** [comment]
Also, don't forget to install the dependencies I mentioned in the readme.

**Comment by SebastianElvis** [comment]
@jcs47 
I changed my bftsmart branch to Zeromq and the HLF's version is your branch. The 4 replicas, proxy and order run well now.
However, when I started the broadcast_timestamp server, the orderer, deliver_stdout crashed and the timestamp server failed to start.
Orderer:
![image](https://user-images.githubusercontent.com/9570153/31094491-5a541b70-a7ad-11e7-82ef-dff9ee1b9243.png)
Deliver_stdout:
![image](https://user-images.githubusercontent.com/9570153/31094513-6b1e2dce-a7ad-11e7-8781-c26fb2e5ca73.png)
Timestamp server:
![image](https://user-images.githubusercontent.com/9570153/31094527-7864a058-a7ad-11e7-9dd7-9f7355a21665.png)
It seems that the system encountered a SIGSEGV signal. What happened when I started the timestamp server?

**Comment by jcs47** [comment]
Did you made sure to re-compile the everything after switching the branch?  You are still using compiled code from the default "master" branch.  I can tell that because the orderer is using the "sendEnvToBFTProxy" method, which does not exist in the zeromq branch. Recompile the fabric code again, and make sure to also re-execute the "go build" command at each of those 3 programs, as described in the readme.

**Comment by SebastianElvis** [comment]
@jcs47 
Thanks for your identification of this error. I did not check out the branch of your HLF repo. Now the system seems to be running!
Another question is that how I can run this BFT orderer in a real distributed environment? I got an array of nodes and hope to deploy a Hyperledger cluster with BFT.

**Comment by jcs47** [comment]
Edit the config/host.config file with the ip address of your hosts, as well as the config/system.config file in case you are using more than 4 nodes (you need to fiddle with the parameters system.servers.num, system.servers.f and system.initial.view).

Before launching the nodes, make sure you delete the config/currentView file. Make also sure that you launch each node in numerical order (node 0, node 1, node 2, etc). The command to launch each node at each machine is:

./startReplica.sh <id> <number of threads> <path to certificate><path to key> <IDs of the bftproxies separated by commas>

A sample command for each node is:

./startReplica.sh 0 10 /home/joao/gocode/src/github.com/hyperledger/fabric/msp/sampleconfig/signcerts/peer.pem /home/joao/gocode/src/github.com/hyperledger/fabric/msp/sampleconfig/keystore/key.pem 1000

./startReplica.sh 1 10 /home/joao/gocode/src/github.com/hyperledger/fabric/msp/sampleconfig/signcerts/peer.pem /home/joao/gocode/src/github.com/hyperledger/fabric/msp/sampleconfig/keystore/key.pem 1000

./startReplica.sh 2 10 /home/joao/gocode/src/github.com/hyperledger/fabric/msp/sampleconfig/signcerts/peer.pem /home/joao/gocode/src/github.com/hyperledger/fabric/msp/sampleconfig/keystore/key.pem 1000

./startReplica.sh 3 10 /home/joao/gocode/src/github.com/hyperledger/fabric/msp/sampleconfig/signcerts/peer.pem /home/joao/gocode/src/github.com/hyperledger/fabric/msp/sampleconfig/keystore/key.pem 1000

To launch the BFTproxy:

java -cp dist/BFT-Proxy.jar:dist/* bft.BFTProxy 1000 9998 9999

Keep in mind that BFTProxy needs to be in the same machine as the Go orderer, but you only need to install the zeromq dependencies in the machine that has the Go orderer and the BFTproxy.

**Comment by SebastianElvis** [comment]
@jcs47 I'm now trying to run the replica in an un-interactive shell by SSH. However it stopped when the first replica was started. Is it feasible for replica/proxy/orderer to run them in the background?

**Comment by jcs47** [comment]
I know that bftsmart can run in the background, but I never tried to execute this entire ordering service that way. I'll need to check it out, but first I need to make sure the master branch is stable and that this code is compatible with the latest HLF code.

**Comment by SebastianElvis** [comment]
@jcs47 I've changed my way to deploy a network manually. There is 4 replicas and 1 proxy/orderer(on the same node), totally 5 nodes.I set the replica's port to 7050(the communication port is automatically set to 7051) but when I tried to test it by `peer node status` command the connection was reset. What's the problem? Thanks for your help!

**Comment by jcs47** [comment]
you'll need to give out more context. I don't understand what `peer node status` is supposed to be.

**Comment by SebastianElvis** [comment]
@jcs47 
The prompt of `peer node status`
![image](https://user-images.githubusercontent.com/9570153/31183238-e416afe6-a91d-11e7-8fc7-4f7ac89935e9.png)
The log of `./startReplica.sh`
![image](https://user-images.githubusercontent.com/9570153/31183319-1a3ca6a2-a91e-11e7-84b1-059170c884ab.png)

The `peer node status` should return that the node is running in normal.

**Comment by jcs47** [comment]
Oh, you mean commands from the HLF framework. That is because the bftsmart library is not prepared to interpret anything else other than messages from bftsmart clients and bftsmart replicas.

**Comment by SebastianElvis** [comment]
@jcs47 Do you mean that the BFTSmart library only supports messages from BFTSmart clients like the timestamp client? Does it support orderer/sample_clients/single_tx_client? I'm doing tests about this consensus mechanism so I want to find a process which can trigger the consensus process. I wonder how I can trigger a transaction.

**Comment by SebastianElvis** [comment]
@jcs47 Also is there a way to benchmark the cluster's throughput? I found a YCSB workload in the config folder, so I thought that a performance test was done by your group. Is it convenient for you to give me some details? I'm really appreciated for your help!

**Comment by jcs47** [comment]
Regarding your first question, the BFT-SMaRt library is only responsible for executing the distributed protocol for atomic broadcast. Furthermore, each BFTNode is implemented on top of that library, and their function is only to take envelopes that have been atomicaly ordered, assembled those envelopes into blocks, sign them, and send them back to the orderer processes (that you invoke by executing orderer/orderer). Try sending those commands to the orderer instead.

As for benchmarks, that YCSB library  is actually one of the dependencies of the BFT-SMaRt library (for one of the demos that uses YCSB) but it is never used in the context of the HLF ordering service. Nonetheless, you can still trigger measurements for throughput by simply keeping sending envelopes to the BFTNodes. Eventually throughput measurements will start popping up at the BFTNodes.
