### ISSUE TITLE
How to change the mandatory delay between block creations?

### ISSUE THREAD

**Issue by gogo9th** [jcs47/hyperledger-bftsmart#11]
Hyperledger seems to enforce minimum 2 seconds (roughly) of delay between block creations. This means that if a node request for a block creation for every 1 second, the node still needs to wait until 2 seconds pass since the latest block creation time. I believe there may be some setting to modify this mandatory delay. I looked through configuration files, but couldn't find the exact parameter for this. Does anyone know? If someone could give me a clue, I would really appreciate it!

**Comment by jcs47** [comment]
You don't need to configure anything related to the batch parameters at java side. The java codebase is given the settings that are present in the fabric configuration files during start up. Hence you have to change it over there.

**Comment by gogo9th** [comment]
I see, but I couldn't find the exact fabric configuration file that is related to this batch parameter (i.e., enforcing roughly minimum 2-second delay between block creations). Could you please tell me which parameter in which configuration is related to this...?

**Comment by jcs47** [comment]
At the configtx.yaml file: https://github.com/jcs47/fabric/blob/release-1.1/sampleconfig/configtx.yaml#L314

**Comment by gogo9th** [comment]
Thanks a lot, it indeed works!  In the past, I tried to modify "BatchTimeout" to 0s, but the mandatory 2-second delay didn't go away. It seems that Fabric ignores 0s and treats it as the default 2s. So now I set the value to 0.01s (very short), and it works fine.
