### ISSUE TITLE
Questions regarding config files and CA

### ISSUE THREAD

**Issue by lu562** [jcs47/hyperledger-bftsmart#13]
Hello,

I succeeded in running bft-smart based on the sampleconfig given in your repo. That is really helpful and thanks a lot.

Now I want to generate my own config files and use them instead of the ones in your sampleconfig folder. In this manner, I plan to use my own CA and my own version of the certificates. Could you describe how can I generate a fresh and working copy of the certificates included in your sampleconfig?

So far, I have already tried to use cryptogen binary to generate the certificate files and use fabric-ca to generate certificate for users/clients. However, so far I always got these errors:

 * When I start the peer: `Cannot run peer because error when setting up MSP of type bccsp from directory /home/lu/gofile/src/github.com/hyperledger/fabric/sampleconfig/msp: the supplied identity is not valid: x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")`
or
`INFO 001 Endorser and orderer connections initialized
Error: got unexpected status: BAD_REQUEST -- error authorizing update: error validating DeltaSet: policy for [Group]  /Channel/Application not satisfied: Failed to reach implicit threshold of 1 sub-policies, required 1 remaining`

I checked these issues online and basically it seems that I didn't generate all these certificates in the right way. Could you share how you generate files in the sampleconfig folder? And how I can reproduce to have my own setting with fresh certificates for CA, orderer and as many peers as desired?

Thanks a lot.

**Comment by jcs47** [comment]
Hi there.

We never had to generate any CA files. The ones in sampleconfig already came with the original release of Fabric v1.1. But there is a development kit called [Fabric-CA](http://hyperledger-fabric-ca.readthedocs.io/en/latest/users-guide.html) that is designed to create certificates. Did you tried it out?

**Comment by lu562** [comment]
Yes, I'm trying to use either fabric-CA or cryptogen to get CA files. Thanks a lot and I will try it again.

**Comment by ricardoxlopes** [comment]
@lu562 Did you find a solution? I was trying to use BYFN with BFTSmart but was giving me this error when creating a new channel:

> [grpc] Printf -> DEBU 003 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:7050: getsockopt: connection refused"; Reconnecting to {127.0.0.1:7050 <nil>}
> 
> Error: failed to create deliver client: orderer client failed to connect to 127.0.0.1:7050: failed to create new connection: context deadline exceeded

Then I tried to create a channel using the node sdk and I was able to connect with the orderer but it is giving me this error:

> [orderer/common/broadcast] Handle -> WARN 018 [channel: testchainid] Rejecting broadcast of config message from 127.0.0.1:56778 because of error: error authorizing update: error validating DeltaSet: policy for [Group]  /Channel/Application not satisfied: Failed to reach implicit threshold of 1 sub-policies, required 1 remaining
> 
> Principal deserialization failure (the supplied identity is not valid: x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com"))

I've already tried with different certificates all generated with cryptogen and gives always the same error. 
@jcs47 Which certificates should I put in the fabric/sampleconfig/msp? In the orderer.yaml the MSP that I used was Org1MSP.
In the bftsamrt project I changed the config/nodeconfig path and msp to Org1MSP also.
The genesis.block seems to be fine as well.

Thank you!

**Comment by lu562** [comment]
@ricardoxlopes  hi, I also used cryptogen to generate certificates and I used msp of peers as fabric/sampleconfig/msp, I also changed admin.pem in admin folder to be pem file of peer. Then it worked for me. While this cryptogen method is really struggling since there is not relevant document. So I'm also not sure if I did everything correctly.
