### ISSUE TITLE
Deploying in distributed environment

### ISSUE THREAD

**Issue by kristycarp** [jcs47/hyperledger-bftsmart#15]
I am trying to use bft-smart to implement a secure blockchain distributed across multiple virtual machines. Following the instructions in the README, I was able to successfully deploy a ledger with four ordering nodes and one frontend within a single VM. However, I am having trouble extending this into an environment that is distributed across VMs. Can anyone give me guidance on how to do this? Is there a common mistake that I am probably making?
If needed, I can give more specifics about how I have implemented the package.
Thank you!

**Comment by jcs47** [comment]
Greetings. This repository has been extensively updated and has now a wiki describing how to deploy this ordering service in a distributed setting.
