### ISSUE TITLE
Error during channel create using nodejs REST API - derer.demandresponse.com              | 2018-07-28 04:20:06.257 UTC [orderer/common/broadcast] Handle -> WARN 0e6 [channel: demandresponsechannel] Rejecting broadcast of config message from 172.18.0.1:39928 because of error: error authorizing update: error validating ReadSet: existing config does not contain element for [Group]  /Channel/Application/ConsumerOrgMSP but was in the read set orderer.demandresponse.com              | 2018-07-28 04:20:06.257 UTC [orderer/common/server] func1 -> DEBU 0e7 Closing Broadcast strea

### ISSUE THREAD

**Issue by sahirvsahirv** [jcs47/hyperledger-bftsmart#16]
The error is similar to the error that got resolved by using a different channelID for genesis block and for channel create

Could you help me understand why it should be so? and what repurcussions does it have?

Thanks

**Comment by jcs47** [comment]
Apologies for late reply. I have not yet tested this codebase with node.js. Could you give me more details on how to reproduce this issue?

**Comment by sahirvsahirv** [comment]
This got solved for me. The channelId for genesis and channel .tx had to be
different.

Now am not able to instantiatr the chain code - the peer is not able to
find the fabric shim etc paths.

I get the issue but not sure how to resolve it.

Any pointers here please.

**Comment by jcs47** [comment]
Have you pulled the latest commits done to this repository? Also, are you making sure to add the frontend address and port to the genesis block when generating it? You have to edit the "Orderer>addresses" parameter for the organization associated with the orderer: https://github.com/jcs47/fabric/blob/release-1.1/sampleconfig/configtx.yaml#L301
