### ISSUE TITLE
Error when setting up a two-org-network with bft-smart

### ISSUE THREAD

**Issue by sysgeass** [jcs47/hyperledger-bftsmart#18]
Thank you so much for providing this fabric-ordering service implementation. 
I have tried the SampleSingleMSPBFTsmart case and it worked, but something goes wrong when I convert my network to a official case with two organizations and four peers. 
I'm confused about the MSP setting for the network. Note that for the SampleSingleMSPBFTsmart profile, all the processes share the same MSP folder, so how can I adjust it to my two-org-network case? 
I have generated new MSPs for the orderer and peers and modified the paths in orderer.yaml and core.yaml, respectively. What should I do about the orderingnodes and frontend? ( For example, do I need to modify the CERTIFICATE, PRIVATE and MSPID parameters in the node.config? )

**Comment by jcs47** [comment]
Hi there. Are you also generating a new genesis block for the system channel? I noticed you did not commented on that. You should also generate a new one that already contains both of your organizations. Make sure to generate it with the configtxgen utility provided with our images, otherwise you will not be able to use the bftsmart orderer type.

**Comment by sysgeass** [comment]
@jcs47 I have generated a new genesis block with the configtxgen utility with your images. So will the orderingnode use the information contained in the genesis block and do I need to set the GENESIS for the path of genesis block?


Another question still:  do I need to modify the CERTIFICATE, PRIVATE and MSPID parameters in the node.config to the new MSP of the orderer generated for the two-org-network? 

Thanks a lot.

**Comment by jcs47** [comment]
> I have generated a new genesis block with the configtxgen utility with your images. So will the orderingnode use the information contained in the genesis block and do I need to set the GENESIS for the path of genesis block?

Yes, it will use the information within the new genesisblock. You will indeed need to set the path for it at config/node.config, paramater GENESIS (or keep the path but replace the file).

> Another question still: do I need to modify the CERTIFICATE, PRIVATE and MSPID parameters in the node.config to the new MSP of the orderer generated for the two-org-network?

If the new genesisblock no longer uses the SampleOrg organization used by default, then yes, you must update those parameters with the crypto material for the organization that is associated with the orderer.

In the coming days I will update the readme with a new section focusing on how to supply a new configuration with multiple organizations and more components. I'll let you know when I am done.

**Comment by sysgeass** [comment]
Thanks!

It will be of great help cause I want to perform a workload test on the bft-smart-based HLF for a standard two-org-network.

**Comment by jcs47** [comment]
Here it is a first version of the instructions: https://github.com/bft-smart/fabric-orderingservice/wiki/Configuring-a-Fabric-deployment

If you think something is unclear, please let me know. Also, a heads up: I recently updated the code to no longer use the CERTIFICATE and PRIVATE parameters in node.config. Now it is necessary to include certificates for all nodes and frontends in ./config/keys, as well as the private key for the particular container. I explain this in more detail in the instructions.
