### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by sa4152** [jcs47/hyperledger-bftsmart#2]
I tried to follow the instruction, but running 'ant' seems to do nothing.

I did : 
clone the two required repositories,
checkout zeromq branch for both,
run ant in hyperledger-bftsmart,
then I ran launch4Replicas.sh with an error saying bft.BFTNode is not found. 

What am I missing?

**Comment by jcs47** [comment]
Did the ant command get to create a ./dist folder with the compiled jar inside? If so, try running these commands instead (one for each different replica):

java -cp dist/BFT-Proxy.jar:lib/* bft.BFTNode 0 10 <path to HLF fork>/msp/sampleconfig/signcerts/peer.pem <path to HLF fork>/msp/sampleconfig/keystore/key.pem 1000,2000

java -cp dist/BFT-Proxy.jar:lib/* bft.BFTNode 1 10 <path to HLF fork>/msp/sampleconfig/signcerts/peer.pem <path to HLF fork>/msp/sampleconfig/keystore/key.pem 1000,2000

java -cp dist/BFT-Proxy.jar:lib/* bft.BFTNode 2 10 <path to HLF fork>/msp/sampleconfig/signcerts/peer.pem <path to HLF fork>/msp/sampleconfig/keystore/key.pem 1000,2000

java -cp dist/BFT-Proxy.jar:lib/* bft.BFTNode 3 10 <path to HLF fork>/msp/sampleconfig/signcerts/peer.pem <path to HLF fork>/msp/sampleconfig/keystore/key.pem 1000,2000

**Comment by sa4152** [comment]
Thanks, at least I was able to pass that stage
