### ISSUE TITLE
How to proof the ordering is based BFT not CFT ? invoke tx in the doc tell us nothing

### ISSUE THREAD

**Issue by JulienGuo** [jcs47/hyperledger-bftsmart#22]

**Comment by jcs47** [comment]
It is based in BFT because it is built on top of the BFT-SMaRt replication library, which is tolerant to Byzantine faults. Its distributed protocol is described and proved in this paper: http://www.navigators.di.fc.ul.pt/wiki/Publication:Joaosousa2011
