### ISSUE TITLE
Can't Run prepare_<TYPE>_defaults.sh scripts contained in the ./docker_images/ folder to obtain the default configuration files for each type of principal (where <TYPE> is either orderingnode,frontend, peer, or cli). 

### ISSUE THREAD

**Issue by JulienGuo** [jcs47/hyperledger-bftsmart#23]

**Comment by JulienGuo** [comment]
Using default tag: latest
Error response from daemon: manifest for bftsmart/fabric-orderingnode:latest not found
./create_orderingnode_container.sh: line 1: ./orderingnode_material/hosts.config: No such file or directory

Unable to find corresponding port to 1001 in hosts.config

**Comment by jcs47** [comment]
Never stumbled upon this problem. Try pulling the latest commits to see if this still persists.
