### ISSUE TITLE
Error docker run "bftsmart/fabric-frontend"

### ISSUE THREAD

**Issue by learnergo** [jcs47/hyperledger-bftsmart#28]
"Could not start connection pool to java component: dial unix /tmp/hlf-pool-9999.sock: connect: no such file or directory"

the error occured when I follow the page "Quick Start v1.2" .
I have another question why there is no the step to create crypto-config.

**Comment by jcs47** [comment]
Hi there. Please provide the rest of the container's output.

Regarding the crypto-config, there is no need to create crypto material while following the Quick Start guide because that material is already available in the containers. But we do explain how to generate new crypto material in the "Configuring a deployment" guide.

**Comment by learnergo** [comment]
Thanks for your reply.I will fill in the other details for you tomorrow.

And I have another question.Can I add or remove orderingnode or fronted anytime ？I have learned the config of orderingnode that has all certs of the others nodes and fronteds.If I want to add a new orderingnode，I have to update other nodes config? Even in consortium ？Is this the official sbft (in the development)?

**Comment by jcs47** [comment]
No, this is not the official sbft. As far as we know, development of that orderer type as been discontinued since well over a year already. This is a third-party, unnoficial ordering service created with the BFT-SMaRt library. Theoretically, it is possible to reconfigure the group of ordering nodes, given that BFT-SMaRt does support reconfiguration of the replica set. But we haven't fully tested this use case yet. In broad terms, it would require an update to the orderer's configuration via a config transation, followed by a reconfiguration to the set of ordering nodes using a BFT-SMaRt client with special previledges.

**Comment by learnergo** [comment]
I will run the test of reconfiguring the group of ordering nodes .
Below is the Error info:
[root@fjr-ofckv-73-121 config]# docker run -i -t --rm --network=bft_network --name=bft.frontend.1000 bftsmart/fabric-frontend:amd64-1.2.0 1000
2018-09-28 11:46:38.917 UTC [localconfig] completeInitialization -> INFO 001 Kafka.Version unset, setting to 0.10.2.0
2018-09-28 11:46:38.982 UTC [orderer/common/server] prettyPrintStruct -> INFO 002 Orderer config values:
	General.LedgerType = "ram"
	General.ListenAddress = "0.0.0.0"
	General.ListenPort = 7050
	General.TLS.Enabled = false
	General.TLS.PrivateKey = "/etc/hyperledger/fabric/tls/server.key"
	General.TLS.Certificate = "/etc/hyperledger/fabric/tls/server.crt"
	General.TLS.RootCAs = [/etc/hyperledger/fabric/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.GenesisMethod = "file"
	General.GenesisProfile = "SampleSingleMSPBFTsmart"
	General.SystemChannel = "test-system-channel-name"
	General.GenesisFile = "/etc/bftsmart-orderer/config/genesisblock"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LogLevel = "info"
	General.LogFormat = "%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}"
	General.LocalMSPDir = "/etc/hyperledger/fabric/msp"
	General.LocalMSPID = "SampleOrg"
	General.BCCSP.ProviderName = "SW"
	General.BCCSP.SwOpts.SecLevel = 256
	General.BCCSP.SwOpts.HashFamily = "SHA2"
	General.BCCSP.SwOpts.Ephemeral = false
	General.BCCSP.SwOpts.FileKeystore.KeyStorePath = "/etc/hyperledger/fabric/msp/keystore"
	General.BCCSP.SwOpts.DummyKeystore =
	General.BCCSP.PluginOpts =
	General.Authentication.TimeWindow = 15m0s
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = "hyperledger-fabric-ordererledger"
	RAMLedger.HistorySize = 1000
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	BFTsmart.ConnectionPoolSize = 10
	BFTsmart.RecvPort = 9999
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
2018-09-28 11:46:38.998 UTC [orderer/bftsmart] newChain -> INFO 003 Creating new bftsmart chain with ID 'bftchannel'
2018-09-28 11:46:38.998 UTC [orderer/commmon/multichannel] NewRegistrar -> INFO 004 Starting system channel 'bftchannel' with genesis block hash af96dbdf7e20915c6687ba74534248906a6bd4c384687266c73a9fa2c877e51b and orderer type bftsmart
2018-09-28 11:46:38.998 UTC [orderer/bftsmart] Start -> INFO 005 Starting new bftsmart chain with ID 'bftchannel'
panic: Could not start connection pool to java component: dial unix /tmp/hlf-pool-9999.sock: connect: no such file or directory

goroutine 1 [running]:
github.com/hyperledger/fabric/orderer/consensus/bftsmart.(*chain).Start(0xc420498d80)
	/go/src/github.com/hyperledger/fabric/orderer/consensus/bftsmart/consensus.go:103 +0xa2b
github.com/hyperledger/fabric/orderer/common/multichannel.(*ChainSupport).start(0xc4205e20a0)
	/go/src/github.com/hyperledger/fabric/orderer/common/multichannel/chainsupport.go:87 +0x34
github.com/hyperledger/fabric/orderer/common/multichannel.NewRegistrar(0x110ba80, 0xc4203f49a0, 0xc4203e6b70, 0x1103380, 0x17699c0, 0xc4200b8ac0, 0x1, 0x1, 0xc42021b260)
	/go/src/github.com/hyperledger/fabric/orderer/common/multichannel/registrar.go:193 +0xec1
github.com/hyperledger/fabric/orderer/common/server.initializeMultichannelRegistrar(0xc4200fe580, 0x1103380, 0x17699c0, 0xc4200b8ac0, 0x1, 0x1, 0xc4203b9ed0)
	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:262 +0x2ee
github.com/hyperledger/fabric/orderer/common/server.Start(0x1065b1c, 0x5, 0xc4200fe580)
	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:102 +0x1d3
github.com/hyperledger/fabric/orderer/common/server.Main()
	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:81 +0x204
main.main()
	/go/src/github.com/hyperledger/fabric/orderer/main.go:15 +0x20

**Comment by learnergo** [comment]
Add ： My system is centos 7.5 

Fellow my step:
```
docker network create -d bridge bft_network
 docker run -i -t --rm --network=bft_network --name=bft.node.0 bftsmart/fabric-orderingnode:amd64-1.2.0 0
docker run -i -t --rm --network=bft_network --name=bft.node.1 bftsmart/fabric-orderingnode:amd64-1.2.0 1
docker run -i -t --rm --network=bft_network --name=bft.node.2 bftsmart/fabric-orderingnode:amd64-1.2.0 2
docker run -i -t --rm --network=bft_network --name=bft.node.3 bftsmart/fabric-orderingnode:amd64-1.2.0 3
```
And when I enter the next command ,the error occured.

```
docker run -i -t --rm --network=bft_network --name=bft.frontend.1000 bftsmart/fabric-frontend:amd64-1.2.0 1000
```
I think it's the java-proxy's fault.

**Comment by jcs47** [comment]
The logs are displaying a pretty strange behavior. While there is plenty of log messages related to the go component, the messages for the java component are not popping up at all. The java component should have been launched first, followed by the go component a few seconds later.

My guess is (and I may be wrong about this), that for some reason your hardware is taking too long to launch the java virtual machine, thus the go component starts first, even though it was launched after.

If I am correct about what is happening, then the latest update to the ordering service might solve the problem. I just implemented a mechanism allowing the go component to explicitly wait for the java component to be available. Pull the docker images again from our repository like this:

```
docker pull bftsmart/fabric-orderingnode:amd64-1.2.0
docker pull bftsmart/fabric-frontend:amd64-1.2.0
```

If you are also using the tools and peer images, pull them as well. Hopefully this solves the issue.

**Comment by learnergo** [comment]
WOW! It works in my mac (linux is in company. It will be seven days before I return to the office)

But I got another error when input bellow:
```
peer chaincode instantiate -o bft.frontend.1000:7050 -C channel47 -n example02 -v 1.2 -c '{"Args":["init","a","100","b","200"]}'
```

**It outputed :**
```
root@8ac120b04538:/# peer chaincode instantiate -o bft.frontend.1000:7050 -C channel47 -n example02 -v 1.2 -c '{"Args":["init","a","100","b","200"]}'
2018-10-01 03:56:55.563 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2018-10-01 03:56:55.565 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
^C
```
**The screen output nothing until I press Ctrl+C. I "docker ps" but can't find the chaincode container.**

**I tried to query the chaincode,returned the error:**
```
root@8ac120b04538:/# peer chaincode query -C channel47 -n example02 -c '{"Args":["query","a"]}'
Error: endorsement failure during query. response: status:500 message:"make sure the chaincode example02 has been successfully instantiated and try again: getccdata channel47/example02 responded with error: could not find chaincode with name 'example02'"
```

**So I instantiate the chaincode again, then get the error:**

```
root@8ac120b04538:/# peer chaincode instantiate -o bft.frontend.1000:7050 -C channel47 -n example02 -v 1.2 -c '{"Args":["init","a","100","b","200"]}'
2018-10-01 04:29:11.448 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2018-10-01 04:29:11.449 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
Error: could not assemble transaction, err Proposal response was not successful, error code 500, msg failed to execute transaction e9ab01f0cb4c6d1fc41c23bdf1fc8d1a58e3f93ce288e6d336a0bf7b068178fe: failed to register example02:1.2 as launching: chaincode example02:1.2 has already been launched
```
**I'm so confused. Besides,it doesn't need ccenv images?**

**Comment by jcs47** [comment]
That initial error when you invoked instantiated for the first time and then hit ctrl+c is not an error. What is happening is that the peer is downloading docker images for ccenv (the place where chaincode is actually executed). You need give it time to end. Try re-deploying the whole system from stratch To make sure you do not get that 500 error again, make sure you delete the image it was downloaded by the peer (you can find it by using `docker images` and then `docker rmi <image ID>`). 

I am going to add a warning to the guide to make people aware of this.

**Comment by learnergo** [comment]
OK,I invoked the chaincode successfully on bft.cli.0. But installing CC on  bft.cli.1 was returned error:
```
Error: error getting chaincode code example02: path to chaincode does not exist: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
```
The bft.cli.1 images doesn't contain chaincode_example02 ?

That's not a big problem.I restarted it and volume the chaincode.

**Comment by jcs47** [comment]
Are you sure you are following the correct guide? You were pushing docker images for Fabric 1.2, but the path you showed now is related to the guide for Fabric v1.1 (which has different paths to the examples).

**Comment by learnergo** [comment]
You write wrong in the page 
```
https://github.com/bft-smart/fabric-orderingservice/wiki/Quick-start-v1.2
```
```
peer chaincode install -n example02 -v 1.2 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
```

**Comment by jcs47** [comment]
Fixed. Sorry about that!

**Comment by learnergo** [comment]
Hello, When I did the upgrade experiment.I again got the error with images  of 1.1.1 :
```
[root@fjr-ofckv-73-121 ~]# docker logs -f 1000.frontend.bft
2018-10-15 02:47:51.422 UTC [orderer/common/server] prettyPrintStruct -> INFO 001 Orderer config values:
	General.LedgerType = "file"
	General.ListenAddress = "0.0.0.0"
	General.ListenPort = 7050
	General.TLS.Enabled = true
	General.TLS.PrivateKey = "/var/hyperledger/orderer/tls/server.key"
	General.TLS.Certificate = "/var/hyperledger/orderer/tls/server.crt"
	General.TLS.RootCAs = [/var/hyperledger/orderer/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.GenesisMethod = "file"
	General.GenesisProfile = "SampleSingleMSPBFTsmart"
	General.SystemChannel = "testchainid"
	General.GenesisFile = "/var/hyperledger/orderer/orderer.genesis.block"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LogLevel = "info"
	General.LogFormat = "%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}"
	General.LocalMSPDir = "/var/hyperledger/orderer/msp"
	General.LocalMSPID = "FrontendsMSP"
	General.BCCSP.ProviderName = "SW"
	General.BCCSP.SwOpts.SecLevel = 256
	General.BCCSP.SwOpts.HashFamily = "SHA2"
	General.BCCSP.SwOpts.Ephemeral = false
	General.BCCSP.SwOpts.FileKeystore.KeyStorePath = "/var/hyperledger/orderer/msp/keystore"
	General.BCCSP.SwOpts.DummyKeystore =
	General.BCCSP.PluginOpts =
	General.BCCSP.Pkcs11Opts =
	General.Authentication.TimeWindow = 15m0s
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = "hyperledger-fabric-ordererledger"
	RAMLedger.HistorySize = 1000
	BFTsmart.ConnectionPoolSize = 10
	BFTsmart.RecvPort = 9999
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
2018-10-15 02:47:51.423 UTC [orderer/common/server] initializeServerConfig -> INFO 002 Starting orderer with TLS enabled
2018-10-15 02:47:51.494 UTC [fsblkstorage] newBlockfileMgr -> INFO 003 Getting block information from block storage
2018-10-15 02:47:51.756 UTC [orderer/bftsmart] newChain -> INFO 004 Creating new bftsmart chain with ID 'testchainid'
2018-10-15 02:47:51.776 UTC [orderer/commmon/multichannel] NewRegistrar -> INFO 005 Starting system channel 'testchainid' with genesis block hash 9c61d89b5820305a97f827341f56dd990630d0bd043726a9a1be82e008ae3e79 and orderer type bftsmart
2018-10-15 02:47:51.777 UTC [orderer/bftsmart] Start -> INFO 006 Starting new bftsmart chain with ID 'testchainid'
panic: Could not start connection pool to java component: dial unix /tmp/hlf-pool-9999.sock: connect: no such file or directory

goroutine 1 [running]:
github.com/hyperledger/fabric/orderer/consensus/bftsmart.(*chain).Start(0xc42007ef40)
	/go/src/github.com/hyperledger/fabric/orderer/consensus/bftsmart/consensus.go:103 +0xa2b
github.com/hyperledger/fabric/orderer/common/multichannel.(*ChainSupport).start(0xc4201b86e0)
	/go/src/github.com/hyperledger/fabric/orderer/common/multichannel/chainsupport.go:87 +0x34
github.com/hyperledger/fabric/orderer/common/multichannel.NewRegistrar(0x10328a0, 0xc4200b0140, 0xc42018f500, 0x102b1e0, 0x1647998, 0xc420196710, 0x1, 0x1, 0xc420239030)
	/go/src/github.com/hyperledger/fabric/orderer/common/multichannel/registrar.go:193 +0xec1
github.com/hyperledger/fabric/orderer/common/server.initializeMultichannelRegistrar(0xc4201cd600, 0x102b1e0, 0x1647998, 0xc420196710, 0x1, 0x1, 0x1)
	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:265 +0x2ee
github.com/hyperledger/fabric/orderer/common/server.Start(0xf95841, 0x5, 0xc4201cd600)
	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:105 +0x1ec
github.com/hyperledger/fabric/orderer/common/server.Main()
	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:84 +0x204
main.main()
	/go/src/github.com/hyperledger/fabric/orderer/main.go:15 +0x20
```
Please help to update the images of 1.1.1 and how to upgrade the network from 1.1.1 to 1.2.Does it support ?

**Comment by jcs47** [comment]
Done. Fetch the images again with `docker pull`.
