### ISSUE TITLE
Fail to configure a Fabric deployment

### ISSUE THREAD

**Issue by learnergo** [jcs47/hyperledger-bftsmart#29]
As follows:
one.
I follow your article to prepare material for "Ordering Nodes and Frontends".When I run the 0.node.bft ,it errored:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./startReplica.sh\": stat ./startReplica.sh: no such file or directory": unknown.
```

?? What's startReplica.sh ??  You never present in the article !!

two.
I go into the containers built by  "Quick start". I find that the contents of "cert0.pem  cert1.pem  cert1000.pem  cert2.pem  cert2000.pem  cert3.pem  cert4.pem  cert7002.pem keystore.pe"  are the same. Why ?

three.
system.config :
system.communication.signatureAlgorithm = SHA512withRSA
RSA ? 

four.
I can't find tls-cert or tls-keystore in peer's container.

Last, the article is so simplify that I can't build my own fabric-net

**Comment by learnergo** [comment]
bft-smart only support non-tls?
Is it eaay to convert smart to pbft?

**Comment by jcs47** [comment]
> What's startReplica.sh ?? You never present in the article !!

`startReplica.sh` is the entrypoint for the node's docker image. It is strange that you are getting such error. Can you provide detailed steps to reproduce that error? Also, what docker version are you using?

> I go into the containers built by "Quick start". I find that the contents of "cert0.pem cert1.pem cert1000.pem cert2.pem cert2000.pem cert3.pem cert4.pem cert7002.pem keystore.pe" are the same. Why ?

They are the same for the sake of making the Quick Start guide as straight forward as possible. These keys were never meant to be used in real deployments. 

> system.config :
> system.communication.signatureAlgorithm = SHA512withRSA
> RSA ?

By default, the BFT-SMaRt library uses RSA keys, hence why that parameter is set to that. But pay attention to the comments regarding that parameter:

> \#Signature algorithm used to verify clients requests and to perform the authenticated Diffie-Hellman exchange during
> \#replica start-up ('SHA512withRSA' is the default value). **_This parameter is overriden in the event that a custom key loader is supplied_**

The codebase for the ordering service does provide a custom key loader  that overrides this parameter, so the algorithm actually  being used is ECDSA.

>I can't find tls-cert or tls-keystore in peer's container.

I'll have to check it out. What if you look for it in the official peer image provided by Hyperledger?

> Last, the article is so simplify that I can't build my own fabric-net

The articles in our wiki assume readers have entry-level knowledge of Hyperledger Fabric. And they mainly  focus on the ordering service, not the whole Fabric network. For that, I would advise you to read the official tutorials here: https://hyperledger-fabric.readthedocs.io/en/release-1.2/

> bft-smart only support non-tls?

It is in our TODO list. The next release of the library will have support for TLS.

> Is it eaay to convert smart to pbft?

BFT-SMaRt is already very similar to PBFT. Converting the normal execution to PBFT is not that hard, but implementing the view change part of the protocol would be pretty challenging.

**Comment by learnergo** [comment]
Thank you for your replay.
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./startReplica.sh\": stat ./startReplica.sh: no such file or directory": unknown.
```
I find the reason caused the error that I uesed "/etc/bftsmart-orderer/config" as NODE_CONFIG_DIR resulting in startReplica.sh not found.
