### ISSUE TITLE
Error   configtxgen  genesisblock

### ISSUE THREAD

**Issue by Acmefocus** [jcs47/hyperledger-bftsmart#37]
root@bft:/etc/hyperledger# configtxgen  -profile BFTGenesis -channelID  channel -outputBlock ./genesisblock
2018-10-22 12:32:56.156 UTC [common/tools/configtxgen] main -> INFO 001 Loading configuration
2018-10-22 12:32:56.184 UTC [common/tools/configtxgen/localconfig] Load -> CRIT 002 Error unmarshaling config into struct:  2 error(s) decoding:

* 'Orderer' has invalid keys: BFTsmart
* 'Profiles[BFTGenesis].Orderer' has invalid keys: BFTsmart
2018-10-22 12:32:56.184 UTC [common/tools/configtxgen] func1 -> CRIT 003 Error unmarshaling config into struct: 2 error(s) decoding:

* 'Orderer' has invalid keys: BFTsmart
* 'Profiles[BFTGenesis].Orderer' has invalid keys: BFTsmart
panic: Error unmarshaling config into struct: 2 error(s) decoding:

* 'Orderer' has invalid keys: BFTsmart
* 'Profiles[BFTGenesis].Orderer' has invalid keys: BFTsmart [recovered]
        panic: Error unmarshaling config into struct: 2 error(s) decoding:

* 'Orderer' has invalid keys: BFTsmart
* 'Profiles[BFTGenesis].Orderer' has invalid keys: BFTsmart

goroutine 1 [running]:
github.com/hyperledger/fabric/vendor/github.com/op/go-logging.(*Logger).Panic(0xc4201c5e00, 0xc420507d60, 0x1, 0x1)
        /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/op/go-logging/logger.go:188 +0xbd
main.main.func1()
        /opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:254 +0x1ae

**Comment by Acmefocus** [comment]
The  configtxgen exec failure   in   bftsmart/fabric-tools: amd64-1.2.0.
I   uses  to  Compiling configtxgen,  it's ok!

**Comment by jcs47** [comment]
I managed to reproduce the problem by using the `configtxgen` tool from the original source code. You have to generate the genesis block using the `configtxgen` tool provided in our bftsmart/fabric-tools` image. From the "Configuring a deployment" guide:

> The first thing to do is to create the crypto material for the organizations and the genesis block for the system channel. You will need to use the official cryptogen tool and the configtxgen tool provided by us. You can access these tools from within a bftsmart/fabric-tools container (or alternatively, by copying the tool from the container to your machine). 

I will edit the wiki to make this more clear.

**Comment by Acmefocus** [comment]
Thanks
