### ISSUE TITLE
bft.frontend.x  msp  *pem  

### ISSUE THREAD

**Issue by Acmefocus** [jcs47/hyperledger-bftsmart#38]
In bft.frontend.2000 , /etc/hyperledger/ fabric/msp/tlscacerts/tlsroot.pem  and 
 /etc/hyperledger/fabric/msp/tlsintermediatecerts/tlsintermediate.pem,
Where are  they  cryptogen  generate file .

**Comment by jcs47** [comment]
I need you to be more clear. I don't understand the question. You mean where is the cryptogen tool within the frontend image? That tools should be available in the bft.cli.0.
