### ISSUE TITLE
Error  create channel

### ISSUE THREAD

**Issue by Acmefocus** [jcs47/hyperledger-bftsmart#40]
root@bft:/etc/hyperledger/fabric# peer channel create -o bft.frontend.1000:7050 -c channel47 -f channel.tx 
2018-10-24 12:49:08.625 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Error: got unexpected status: BAD_REQUEST -- error authorizing update: error validating DeltaSet: policy for [Group]  /Channel/Application not satisfied: Failed to reach implicit threshold of 1 sub-policies, required 1 remaining
root@bft:/etc/hyperledger/fabric# exit

**Comment by jcs47** [comment]
Have you gotten this error while following the Quick Start guide? If not, what is the sequence of steps you took to get this error?
