### ISSUE TITLE
New ordering nodes/peers/frontends

### ISSUE THREAD

**Issue by seuho2003** [jcs47/hyperledger-bftsmart#45]
Hello, I'm new to this bft-smart ordering service system.

I just successfully brought up a sample HLF network with the BFT ordering service on my computer, thanks to the quick start guide.

But I'm having difficulty reconfiguring(for new peers, frontends, etc.) this sample network, so I'd like to ask you some questions.

I know I need to modify some configuration files(crypto-config.yaml, etc.) in order to add new peers/frontends, but I can't find where the files are, which have been used for bringing up the sample network on the quick start guide page(it seems that I even don't have any configuration files).

Could you please tell me where I find them or how I can bring up a network with this BFT ordering service with sample files/templates in my computer(so that I modify the crypto-config.yaml)?

I'm looking forward to your response. Thank you!

**Comment by jcs47** [comment]
Hi there,

The files used in the crypto material used in the quick start guide are the ones in the /fabric/sampleconfig directory that exists both in the official fabric repository and our own fork:

https://github.com/jcs47/fabric/tree/release-1.3/sampleconfig

Notice that what is being done is  that all processes use the same MSP and the same key pairs. This is obviously something that should not be done in a real deployment, but it keeps the quick start guide as simple to use.

Also noticed that the keys used in the nodes/frontends containers, in the directory /orderingservice/config/keys are the same as in the aforementioned fabric directory, but with different names. 

Finally, to set up a real deployment with additional frontends, peers, etc, you can read  [this guide](https://github.com/bft-smart/fabric-orderingservice/wiki/Configuring-a-deployment-v1.3).

**Comment by seuho2003** [comment]
Hello.

Thank you for your reply.

I've taken a look at the configuring a deployment page you mentioned, and have tried to add new frontends and peers.

I defined one new peer/one new frontend in the configuration files respectively, however, I just ran into a problem when using 'configtxgen' tool.

I copied that tool from a bft-tool container as it says, and executed this command through the configtxgen tool for a genesis block:
$configtxgen` -channelID mychannel -profile BFTGenesis -configpath '...../configtx.yaml' -outputBlock '..../config'

This error message is shown:
.... [common/tools/configtxgen] main -> INFO 001 Loading configuration
.... [common/tools/configtxgen/localconfig] Load -> PANI 002 Error reading configuration:  Unsupported Config Type ""
.... [common/tools/configtxgen] func1 -> PANI 003 Error reading configuration:  Unsupported Config Type ""
panic: Error reading configuration:  Unsupported Config Type "" [recovered]
     panic: Error reading configuration:   Unsupported Config Type ""

export FABRIC_CFG_PATH=$PWD also has been used.

I'd really like to learn how to bring up/reconfigure this network.

Could you please tell me how to resolve that error if possible?

Thank you for your help!
