### ISSUE TITLE
Which pem file should I use to replace the original keystore.pem?

### ISSUE THREAD

**Issue by seuho2003** [jcs47/hyperledger-bftsmart#48]
Hello.

Thank you for your reply a few days ago.

As I asked, I'm trying to add one more new frontend/peer each in my network.

On the configuring a deployment page, it says:
Place the private key for the frontend/ordering node, as well as all certificates for both ordering nodes and frontends at ./<TYPE>_material/config/keys. Rename each certificate generated with cryptogen to cert<ID>.pem, and the private key to keystore.pem. The contents of the directory should look as follows:

I just successfully generated certificates and keys for the new nodes, however, I was not able to bring up an ordering node container with the error message:
Exception in thread "main" java.lang.ClassCastException: org.bouncycastle.cert.X509CertificateHolder cannot be cast to org.bouncycastle.openssl.PEMKeyPair

I think that's because of new .pem files I have replaced, but I have no idea which .pem file I'm supposed to use because a lot of .pem files were generated in the "./crypto-config/ordererOrganizations" directory.

That folder looks like:
frontend.bft, node.bft

each folder has:
ca, msp, orderers, tlsca, users
etc..

It may bother you, but could you please tell me which pem files should I use?(esp keystore.pem file.. Whose private key should I use? Should I replace it each time I bring up a node?)

I really appreciate if you answer my question.

Thank you!

**Comment by jcs47** [comment]
The key files you need to copy are in the "orderers" sub-directory of each "node.bft" and "frontend.bft" directory. For instance, for node `0.node.bft`, its public key is in `node.bft/orderes/0.node.bft/ms/signcert`, and its private key is in `node.bft/orderes/0.node.bft/ms/keystore`

**Comment by jjbaek35** [comment]
@jcs47, In your wiki description, you mentioned we should put the private key and certs at ./<TYPE>__material/config/keys  by renaming as cert<id>.pem and keystore.pem. 
As you said I can find 0.node.bft-cert.pem, 1.node.bft-cert.pem, 2.node.bft-cert.pem,  and 3.node.bft-cert.pem.  I renamed these as cert0.pem, cert1.pem, cert2.pem, and cert3.pem respectively.
BTW, how about the secret key for each.  You mentioned only one keystore.pem.
But I have 4 keys respectively. which one can be the keysotre.pem?

Additionally, what about the other pem file like ca.node.bft-cert.pem and Admin@node.bft-cert.pem.
Do I have to stay these at ./keys?
