### ISSUE TITLE
Fatal error when initializing core config

### ISSUE THREAD

**Issue by HaoJiawang** [jcs47/hyperledger-bftsmart#50]
In core.yaml, I changed `peer->gossip->bootstrap` to
 ```
 0.peer.lasige.bft:7051
 1.peer.lasige.bft:7051
 0.peer.ibm.bft:7051
 1.peer.ibm.bft:7051
```
I also changed `peer->gossip->endpoint` to
```
 0.peer.lasige.bft:7051
 1.peer.lasige.bft:7051
 0.peer.ibm.bft:7051
 1.peer.ibm.bft:7051
```
when I run `docker start -a 0.peer.lasige.bft`, error occurs 
`2018-12-05 12:21:54.873 UTC [main] InitCmd -> ERRO 001 Fatal error when initializing core config : error when reading core config file: While parsing config: yaml: line 133: found character that cannot start any token`

**Comment by jcs47** [comment]
Check the file for blanklines that are actually filled with spaces. The yaml format does not handle those lines well.

**Comment by HaoJiawang** [comment]
@jcs47 Yes, I used a Tab and it caused this error. Thank you a lot for your help! 
However, when I create a new channel, there is a new error. Do you know what is wrong with my configtx.yaml?
```
2018-12-07 12:17:28.562 UTC [common/tools/configtxgen] main -> INFO 001 Loading configuration
2018-12-07 12:17:28.568 UTC [common/tools/configtxgen/localconfig] Load -> PANI 002 Error reading configuration:  Unsupported Config Type ""
2018-12-07 12:17:28.568 UTC [common/tools/configtxgen] func1 -> PANI 003 Error reading configuration:  Unsupported Config Type ""
```
