### ISSUE TITLE
Can I verify BFT fault tolerance using the network in "quick start"? 

### ISSUE THREAD

**Issue by HaoJiawang** [jcs47/hyperledger-bftsmart#52]
I have started the network in "quick start" and I can query and invoke the chaincode. Can I verify BFT fault using this network?

**Comment by jcs47** [comment]
I am not sure I understand what you mean. Can you be more specific?

**Comment by HaoJiawang** [comment]
@jcs47 In step 10，I found that crashed nodes can be restarted.

> Each ordering node can be re-started after a crash, as long as the total number of simultaneously crashed nodes do not exceed f.

But I don't know how to crash a node myself. What I want to do is verifing that order service is still working when there is a crash node. Can I finish this experiment using the network in ‘quick start’?
