### ISSUE TITLE
About startWorkload.sh  

### ISSUE THREAD

**Issue by gold9450412** [jcs47/hyperledger-bftsmart#56]
Hello,
I run startWorkload.sh 
This is my command :  startWorkload.sh 1000 channel47 2 80 80 unsigned 50 
 
but  i get throughput_NODE_ID_IS_UNDEFINED.log  and latency_1000.log
The throughput_NODE_ID_IS_UNDEFINED.log and latency_1000.log are empty.

May I know why this happens? I want to measurements performance.

Thanks for your time in advance.

The following is my node.config
------------------------------------------------------------------------------------------
#Path to the genesis block for the system channel
GENESIS=/bft-config/genesisblock

#The ID of the membership service provider (MSP)
MSPID=NodesMSP

#Number of block generation threads in the pool
PARELLELISM=10

#Maximum number of blocks to submit to each signer/sending thread
BLOCKS_PER_THREAD=10000

#IDs of the frontends present in the system, separate by commas
RECEIVERS=1000,2000,3000

#Filter malformed envelopes. If this option is disabled but ENV_VALIDATION is enabled, such envelopes will eventually be discarded during validation
FILTER_MALFORMED=false

#Enable/disable envelope validation. Configuration envelopes are always verified regardless of this parameter
ENV_VALIDATION=false

#Enable/disable second block signature. Useful for benchmarking, but it must be enabled on production deployments, so that it abides to Fabric's implementation
BOTH_SIGS=true

#The acceptable difference between the state machine's time and the client's time. Only used if envelope validation is active
#or in the case of a reconfiguration envelope
TIME_WINDOW=15m

#Calculate throughput measurements every THROUGHPUT_INTERVAL envelopes/blocks
THROUGHPUT_INTERVAL=500

**Comment by metodiistatkov** [comment]
I am facing the same issue. Have you found any solution for it yet?
