### ISSUE TITLE
About the installation 

### ISSUE THREAD

**Issue by lu562** [jcs47/hyperledger-bftsmart#8]
Hi,
    I tried to pull your repo and get bft-smarting working on hyperledger 1.1.
    I carefully followed the instruction and everything worked fine until I run the command to create channel.
    I tried for several time and get the same error:
    
This is the command I run:

    ford@ford-VirtualBox:~/gofile/src/github.com/hyperledger/fabric$ ./build/bin/peer channel create -o 127.0.0.1:7050 -c tempd -f /home/ford/gofile/src/github.com/hyperledger/fabric/cc.tx 

This is the error:

2018-01-31 12:26:19.106 EST [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Error: Got unexpected status: BAD_REQUEST -- Error authorizing update: Error validating ReadSet: Existing config does not contain element for [Groups] /Channel/Application but was in the read set

any ideas? Thanks.

**Comment by jcs47** [comment]
I tried to reproduce the problem in my end, but the closest I got was this:

```
Error: got unexpected status: BAD_REQUEST -- error authorizing update: error validating ReadSet: existing config does not contain element for [Group]  /Channel/Application/SampleOrg but was in the read set
```

I did this by editing the `SampleSingleMSPBFTsmart` profile in `fabric/sampleconfig/configtx.yaml` (I removed the "SampleOrg" line from `Consortiums > SampleConsortium > Organizations`). This suggests that the `configtx.yaml` file that you used to generate `cc.tx` might be different from the one used to generate the genesis file.  Are you sure the orderer is loading the correct genesis block? Check the `General > GenesisFile` parameter in the orderer.yaml file. Is `General > GenesisMethod` set fo "file" too?

**Comment by lu562** [comment]
Hi, Thanks a lot for the reply.

Here is part of my orderer.yaml, I think it is properly set.


`# Genesis method: The method by which the genesis block for the orderer
    # system channel is specified. Available options are "provisional", "file":
    #  - provisional: Utilizes a genesis profile, specified by GenesisProfile,
    #                 to dynamically generate a new genesis block.
    #  - file: Uses the file provided by GenesisFile as the genesis block.
    GenesisMethod: file

    # Genesis profile: The profile to use to dynamically generate the genesis
    # block to use when initializing the orderer system channel and
    # GenesisMethod is set to "provisional". See the configtx.yaml file for the
    # descriptions of the available profiles. Ignored if GenesisMethod is set to
    # "file".
    GenesisProfile: SampleMSPBFTsmart

    # Genesis file: The file containing the genesis block to use when
    # initializing the orderer system channel and GenesisMethod is set to
    # "file". Ignored if GenesisMethod is set to "provisional".
    GenesisFile: /home/ford/gofile/src/github.com/hyperledger/fabric/genesis.block
`

**Comment by lu562** [comment]
How can I decide which config file to use for generating CreateChannelTx or genesis block?
Is it envirionment viable $FABRIC_CFG_PATH?I can see I already set this viable through echo command:

```
ford@ford-VirtualBox:~/gofile/src/github.com/hyperledger/fabric$ echo $FABRIC_CFG_PATH
/home/ford/gofile/src/github.com/hyperledger/fabric/sampleconfig/
```

**Comment by jcs47** [comment]
In the context of these installation instructions, you use the same config file to generate both the CreateChannelTx  and the genesis file (the ones inside ./fabric/sampleconfig). Make sure you are using the "release-1.1" branch both for the ordering service repository and the HLF fork referenced in the instructions. If you are using multiple terminals, make sure that $FABRIC_CFG_PATH is set across all of them (even if you use the "export" command set the variable, it might only be set in the terminal you input that command).

**Comment by lu562** [comment]
Thanks. I think I set it up correctly but error still happens. Let me build up a clean environment and redo all these steps again.

**Comment by lu562** [comment]
Hi,
One of my college tried this setup in his machine and he encounters the same problem as mine. Now the guess is we might meet some problems regarding the configtx.yaml. To solve this could you give us a copy of the following files so that we can track this problem?
-the sample config file you use
-genesis block, channel creation block,anchor block together with the channel id corresponding to these blocks.

Appreciate it a lot and my email address is lu562@purdue.edu.

**Comment by jcs47** [comment]
Here it is the ./sampleconfig folder and the artifacts created:

https://www.dropbox.com/s/dumlbx9w8u2iuqp/fabric.tar.gz?dl=0

The channel ID used for the artifacts is "channel47"

**Comment by lu562** [comment]
Thanks a lot! I'm still testing but one thing for sure is that the files you provide are different from files on github repo.  Are you sure everything on github is up to date?

**Comment by lu562** [comment]
And when I tried to use configtxgen(provided in your HLF 1.1 version) to generate ChannelCreationTx using the config files that you just provided , a lot of version mismatch errors occur,here is a shot on that:


ford@ford-VirtualBox:~/gofile/src/github.com/hyperledger/fabric$ ./build/bin/configtxgen -profile SampleSingleMSPChannel -outputCreateChannelTx channel.tx -channelID channel47
2018-02-05 16:35:10.398 EST [common/tools/configtxgen] main -> INFO 001 Loading configuration
2018-02-05 16:35:10.597 EST [common/tools/configtxgen/localconfig] Load -> CRIT 002 Error unmarshaling config into struct:  10 error(s) decoding:

* '' has invalid keys: capabilities
* 'Profiles[SampleDevModeKafkaV1_1].Orderer' has invalid keys: Capabilities
* 'Profiles[SampleDevModeSoloV1_1].Orderer' has invalid keys: Capabilities
* 'Profiles[SampleSingleMSPBFTsmartV1_1]' has invalid keys: Capabilities
* 'Profiles[SampleSingleMSPBFTsmartV1_1].Orderer' has invalid keys: Capabilities
* 'Profiles[SampleSingleMSPChannelV1_1].Application' has invalid keys: Capabilities
* 'Profiles[SampleSingleMSPKafkaV1_1]' has invalid keys: Capabilities
* 'Profiles[SampleSingleMSPKafkaV1_1].Orderer' has invalid keys: Capabilities
* 'Profiles[SampleSingleMSPSoloV1_1]' has invalid keys: Capabilities
* 'Profiles[SampleSingleMSPSoloV1_1].Orderer' has invalid keys: Capabilities


So I guess maybe files in github repo is not up to date. Or did I miss something? Thanks.

**Comment by jcs47** [comment]
I fetched the files from the master branch instead of the release branch. Here it is the proper files:

https://www.dropbox.com/s/p5h2fhddg5239x1/fabric-release1.1.tar.gz?dl=0

**Comment by lu562** [comment]
Thanks for providing these files. 
While now the problems seem weird: When I use the genesisblock and channel.tx that you directly provided, everything works well. And I also checked that the config files in samplecomfig folders are consistent. While when I use configtxgen to generate my own genesisblock then use this block to launch everything , error just happens like before.
So now I doubt the binary "configtxgen" which I use may have some problems. I simply got it by compiling your HLF1.1 repo. Is there anything I need to take care when comliling HLF? Thanks.

**Comment by jcs47** [comment]
The only thing that is necessary to do before compiling is to run the ./devenv/setupUbuntuOnPPC64le.sh script and install all the dependencies, but if you can compile HLF you already did that at this point. 

Have you tried comparing the contents of both genesis blocks to see in what way the contents diverge from each other? You can do that by executing `./configtxgen -inspectBlock <path to block>`. You can also do the same for the channel creation transaction using the `-inspectChannelCreateTx` flag.

**Comment by lu562** [comment]
Hi, I compared the two genesisblocks and here is the difference:



diff blockinfo1 blockinfo2
451c451
< 							"channel_id": "jcschannel",

\> 							"channel_id": "channel47",
453,454c453,454
< 							"timestamp": "2018-02-05T22:09:19.000Z",
< 							"tx_id": "369f5abbdea4e9a6613540df82fe58d889ef9f8a26d040a0e75cf36e42070bf8",

\> 							"timestamp": "2018-02-08T21:34:17.000Z",
\> 							"tx_id": "961009112c02022fb13b034dd1686fd8a6874ac54a21026047d650c5881aca55",
459c459
< 							"nonce": "jSAzsYJQbc5dzs8sxjHZDHMUKsis38QN"

\> 							"nonce": "gLxQUUjYMBAHhi9mF7opOR6LDId2lf50"
467c467
< 		"data_hash": "Rp7pNsMiEuTUfkproK69AikSfMaY7hh6P3ZzQL2dml0=",

\> 		"data_hash": "CmUjlWZScpxjSiqyvXkp9px1zz4YgzAfIcajSIOXprQ=",

So I think the main difference is that the genesisblock you provide has channel id "jcschannel" while mine has "channel47". But this makes things more wired since I start everything using your block and channelID "channel47" successfully.... If using my block I will meet the same error as in the title.

So is there any tricks about the channelID or is it hardcoded somewhere?
Thanks a lot :)

**Comment by jcs47** [comment]
Wait a second, are you using the same channel ID to create both the genesisblock and also the channel creation ID? You can't do that. When creating the genesis block, you supply the ID for the *system channel*, while when creating the channel transaction, you are creating a *new channel for a another network*.

Here it is a sample execution I use:

```
#create artifacts
cd /home/joao/gocode/src/github.com/hyperledger/fabric/build/bin

./configtxgen -profile SampleSingleMSPBFTsmart -channelID jcschannel -outputBlock ../../genesisblock
./configtxgen -profile SampleSingleMSPChannel -outputCreateChannelTx ../../channel.tx -channelID channel47
./configtxgen -profile SampleSingleMSPChannel -outputAnchorPeersUpdate ../../sampleorg.tx -channelID channel47 -asOrg SampleOrg

#launch the ordering service (java processes)
cd /home/joao/NetBeansProjects/BFT-Proxy

#the following 5 lines are typed each one in a seperate terminal, but in same directory
rm config/currentView ; ./startReplica.sh 0
/startReplica.sh 1
/startReplica.sh 2
/startReplica.sh 3
./startFrontend.sh 1000 10 9999

#launch the ordering service (golang, another terminal)
cd /home/joao/gocode/src/github.com/hyperledger/fabric/build/bin
./orderer start

#launch the peer (another terminal, same directory)
./peer node start

#client commands (another terminal, same directory)

./peer channel create -o 127.0.0.1:7050 -c channel47 -f ../../channel.tx
./peer channel join -b channel47.block
./peer channel update -o 127.0.0.1:7050 -c channel47 -f ../../sampleorg.tx
./peer chaincode install -n mycc -v 1.0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
./peer chaincode instantiate -o 127.0.0.1:7050 -C channel47 -n mycc -v 1.0 -c '{"Args":["init","a","100","b","200"]}'
./peer chaincode query -C channel47 -n mycc -v 1.0 -c '{"Args":["query","a"]}'
./peer chaincode invoke -C channel47 -n mycc -v 1.0 -c '{"Args":["invoke","a","b","10"]}'
./peer chaincode query -C channel47 -n mycc -v 1.0 -c '{"Args":["query","a"]}'
./peer chaincode invoke -C channel47 -n mycc -v 1.0 -c '{"Args":["invoke","a","b","10"]}'
./peer chaincode query -C channel47 -n mycc -v 1.0 -c '{"Args":["query","a"]}'
```

**Comment by jcs47** [comment]
By the way, I just tried executing these steps using the same channel ID for both the genesisblock and the channel transaction, and I managed to successfully reproduce the original error message.

**Comment by lu562** [comment]
Thanks a lot! Now it makes perfect sense.

**Comment by george321** [comment]
Hello i followed your steps [here](https://github.com/jcs47/hyperledger-bftsmart/issues/8#issuecomment-364271529) but in that step #launch the peer (another terminal, same directory)
./peer node start

i get the follow wing result:
`mitaros@dsg2:~/GoProjects/src/github.com/hyperledger/fabric/build/bin$ export FABRIC_CFG_PATH=$GOPATH/src/github.com/hyperledger/fabric/sampleconfig/
mitaros@dsg2:~/GoProjects/src/github.com/hyperledger/fabric/build/bin$ sudo ./peer node startpanic: Fatal error when initializing core config : Error when reading core config file: Unsupported Config Type ""


goroutine 1 [running]:
main.main()
	/home/mitaros/GoProjects/src/github.com/hyperledger/fabric/peer/main.go:94 +0x78b
mitaros@dsg2:~/GoProjects/src/github.com/hyperledger/fabric/build/bin$ 
`

any ideas?
